# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ccfdab8dbcce589797ddcbe623c825ace485f84ca57330ec5fb43195b85fe4506e199f0dfb3268ce1af721454aa9a9325fa0299ff89cb8073f5943d8ece64f9

test:
  secret_key_base: 4c23683b61179f34692a2db2c988258899846de1a1d9dc7df14d1947998d46d32d33f21277744a0ff02e7546011c88c35a1da166ba9c8f8fa3011decaaac42e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
